# Cloud Foundry Java Buildpack
#
# Configuration for the CF Metrics Exporter javaagent.
# You can override values here using the environment variable:
#   JBP_CONFIG_CF_METRICS_EXPORTER
# Example:
#   cf set-env my-app JBP_CONFIG_CF_METRICS_EXPORTER '{ version: 0.6.2, uri: "https://.../cf-metrics-exporter-0.6.2.jar" }'
---
cf_metrics_exporter:
  version: +
  repository_root: "https://raw.githubusercontent.com/rabobank/java-buildpack/main/cf-metrics-exporter/{platform}/{architecture}"
